name: Latest Blog Posts
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *'
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-blog-posts:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    environment: 'UPDATE POSTS'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in latest blog posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://jinseong-dev.tistory.com/rss"
